### ISSUE TITLE
Initial transactions.data file creation issue

### ISSUE THREAD

**Issue by DmitryRendov** [EtienneDx/RealEstate#16]
```
[11:43:17 WARN]: java.nio.file.NoSuchFileException: plugins\RealEstate\transactions.data
[11:43:17 WARN]:        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
[11:43:17 WARN]:        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[11:43:17 WARN]:        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[11:43:17 WARN]:        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
[11:43:17 WARN]:        at java.nio.file.Files.newByteChannel(Unknown Source)
[11:43:17 WARN]:        at java.nio.file.Files.newByteChannel(Unknown Source)
[11:43:17 WARN]:        at java.nio.file.Files.readAllBytes(Unknown Source)
[11:43:17 WARN]:        at me.EtienneDx.RealEstate.Transactions.TransactionsStore.loadData(TransactionsStore.java:82)
[11:43:17 WARN]:        at me.EtienneDx.RealEstate.Transactions.TransactionsStore.<init>(TransactionsStore.java:37)
[11:43:17 WARN]:        at me.EtienneDx.RealEstate.RealEstate.onEnable(RealEstate.java:89)
[11:43:17 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:43:17 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[11:43:17 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435)
[11:43:17 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
[11:43:17 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
[11:43:17 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482)
[11:43:17 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[11:43:17 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885)
[11:43:17 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by EtienneDx** [comment]
Fixed by commit 16a581f
