### ISSUE TITLE
1.16?

### ISSUE THREAD

**Issue by Valareos** [EtienneDx/RealEstate#23]
Will this work with 1.16? or is it a matter of me trying it and letting you know if it works or not?

**Comment by EtienneDx** [comment]
I'm rather busy right now so I'll appreciate if you could try it out and report wether it works or not.
I'd like to find some time towork on this but it's rather complicated right now...

**Comment by Valareos** [comment]
`[22:31:11] [Server thread/ERROR]: Error occurred while enabling RealEstate v1.1.1 (Is it up to date?)
java.lang.NoSuchFieldError: addonPlugins
        at me.EtienneDx.RealEstate.RealEstate.onEnable(RealEstate.java:105) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:493) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:407) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:438) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

Attempted with both updated version of GriefPrevention and the version supplied on this repo.

**Comment by EtienneDx** [comment]
I'll have to take a look, the error seems to be with the link with grief prevention, which is still a modified version until the release of the next major GP, which should take a while still as I recall...

**Comment by Vilevar** [comment]
GP removed your addon system so because you're busy I think I'm going to create a pull request for GP that adds events which I'm going to use for a pull request for this 1.16 update if you agree.

**Comment by EtienneDx** [comment]
Sounds great to me 👍 I hope to get back to plugin dev soon but can’t promise anything...

**Comment by JxM-92** [comment]
I hope you can get back to work on this plugin soon...

**Comment by EtienneDx** [comment]
I'm getting back to it right now @JxM-92, I'll need to find a few testers but should be a matter of days max

**Comment by EtienneDx** [comment]
Just updated my test server with the latest build for 1.16.3, hopefully I'll upload a working version here in a day or two

**Comment by EtienneDx** [comment]
Until further bugs, this issue is now fixed by the 1.2.3 version

**Comment by JxM-92** [comment]
oh great, sorry for the late response... will try it... but I have a question, because this is my first time finding out this plugin, the modified GP offered won't have issues with the "official" one, right? I mean with the config files, I don't understand why there are 2 "different versions" of the same plugin and not just using, e.g., the modified one as the "official" one... not trying to be rude or anything, if I have to use it then I will, just trying to understand... will the offered modified GP work well with other add-ons? I'm using GP-teleport add-on too for example... 

This is also an issue that could be confusing for other people... that's why it would be good to add this info a lil'bit more explained...😅

**Comment by JxM-92** [comment]
oh great, thanks... I hope the offered modified GP will be merge soon so it won't need a customize dependency... 😅

**Comment by EtienneDx** [comment]
I’m working on it, but some of the modifs need to be re wrote to match GP current coding style and evolution direction, and that’s a lot of work which would require more time than a Minecraft open source plugin can offer ^^’

**Comment by JxM-92** [comment]
oh I get it... thanks... just tried it on my 1.16.2 server and it worked well...
