### ISSUE TITLE
Can't buy claim

### ISSUE THREAD

**Issue by DooSHeK2** [EtienneDx/RealEstate#42]
When I want to buy a claim, after clicking on the sign in the console I have this error:

`[Server thread/ERROR]: Could not pass event PlayerInteractEvent to RealEstate v1.4.0-pre1
java.lang.IllegalArgumentException: Illegal group reference: group index is missing
	at java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1029) ~[?:?]
	at java.util.regex.Matcher.appendReplacement(Matcher.java:997) ~[?:?]
	at java.util.regex.Matcher.replaceAll(Matcher.java:1181) ~[?:?]
	at java.lang.String.replaceAll(String.java:2939) ~[?:?]
	at me.EtienneDx.RealEstate.Messages.getMessage(Messages.java:449) ~[RealEstate-1.4.0-pre1.jar:?]
	at me.EtienneDx.RealEstate.Messages.getMessage(Messages.java:440) ~[RealEstate-1.4.0-pre1.jar:?]
	at me.EtienneDx.RealEstate.Messages.sendMessage(Messages.java:461) ~[RealEstate-1.4.0-pre1.jar:?]
	at me.EtienneDx.RealEstate.Messages.sendMessage(Messages.java:456) ~[RealEstate-1.4.0-pre1.jar:?]
	at me.EtienneDx.RealEstate.Transactions.ClaimSell.interact(ClaimSell.java:138) ~[RealEstate-1.4.0-pre1.jar:?]
	at me.EtienneDx.RealEstate.REListener.onPlayerInteract(REListener.java:422) ~[RealEstate-1.4.0-pre1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor212.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-205]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[paper-1.18.1.jar:git-Paper-205]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:542) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1840) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-205]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1414) ~[paper-1.18.1.jar:git-Paper-205]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-205]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-205]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-205]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-205]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-205]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-205]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

Griefprevention: 16.18-RC1
RealEstate: 1.4.0-pre1
Server: paper-1.18.1-205

**Comment by EtienneDx** [comment]
Hi, thanks for the report, I think I found the bug and managed to fix it. My guess is that you're using a $ symbol in your currency, which messes with the way the code is handled. I'll work on fixing it.

**Comment by EtienneDx** [comment]
Could you try the version 1.4.0-pre2 and confirm the bug is fixed please? I'm kind of short on time so I cannot test thoroughly all features and would really appreciate a hand to validate everything is working

**Comment by DooSHeK2** [comment]
Made a quick test and it seems to work now.
