### ISSUE TITLE
Error using /re renewrent enable|disable

### ISSUE THREAD

**Issue by SrBedrock** [EtienneDx/RealEstate#50]
If the player rents a land and uses the `/re renewrent disable` or `/re renewrent enable` inside the land, an error is sent to the console:

```
[17:30:39 INFO]: ThiagoROX issued server command: /re renewrent disable
[17:30:39 ERROR]: [RealEstate] [ACF] Exception in command: re renewrent disable
[17:30:39 ERROR]: [RealEstate] [ACF] java.lang.NullPointerException: Cannot invoke "java.util.UUID.equals(Object)" because "cr.buyer" is null
[17:30:39 ERROR]: [RealEstate] [ACF]    at RealEstate-1.4.0.jar//me.EtienneDx.RealEstate.RECommand.renewRent(RECommand.java:176)
[17:30:39 ERROR]: [RealEstate] [ACF]    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:30:39 ERROR]: [RealEstate] [ACF]    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[17:30:39 ERROR]: [RealEstate] [ACF]    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:30:39 ERROR]: [RealEstate] [ACF]    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[17:30:39 ERROR]: [RealEstate] [ACF]    at RealEstate-1.4.0.jar//me.EtienneDx.RealEstate.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[17:30:39 ERROR]: [RealEstate] [ACF]    at RealEstate-1.4.0.jar//me.EtienneDx.RealEstate.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[17:30:39 ERROR]: [RealEstate] [ACF]    at RealEstate-1.4.0.jar//me.EtienneDx.RealEstate.acf.BaseCommand.execute(BaseCommand.java:513)
[17:30:39 ERROR]: [RealEstate] [ACF]    at RealEstate-1.4.0.jar//me.EtienneDx.RealEstate.acf.RootCommand.execute(RootCommand.java:99)
[17:30:39 ERROR]: [RealEstate] [ACF]    at RealEstate-1.4.0.jar//me.EtienneDx.RealEstate.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[17:30:39 ERROR]: [RealEstate] [ACF]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[17:30:39 ERROR]: [RealEstate] [ACF]    at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905)
[17:30:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2298)
[17:30:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2109)
[17:30:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2090)
[17:30:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[17:30:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[17:30:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[17:30:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:30:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[17:30:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[17:30:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1403)
[17:30:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189)
[17:30:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[17:30:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1380)
[17:30:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1373)
[17:30:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[17:30:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1351)
[17:30:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1233)
[17:30:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319)
[17:30:39 ERROR]: [RealEstate] [ACF]    at java.base/java.lang.Thread.run(Thread.java:833)
```
Error in-game:

![image](https://user-images.githubusercontent.com/51332006/159079273-2d4ef5f2-c85f-4f51-a580-1e266da163f3.png)

**Comment by EtienneDx** [comment]
Damn I thought that was finished for good...
I'm kinda in a rush week rn but I'll add it to the board

**Comment by EtienneDx** [comment]
> Any updates on this? I'm having the exact same error.

Haven't had any free time lately, I'll fix this asap
