### ISSUE TITLE
[Bug] NPE when run any command outside of a claim v1.5.0-pre1

### ISSUE THREAD

**Issue by SrBedrock** [EtienneDx/RealEstate#59]
When executing `/re bid`, `/re info`, `/re cancel`, `/re renewrent`, `/re renewrent` and `/re exitoffer` outside of a claim the error is sent to the console:

```
[14:59:24 ERROR]: [RealEstate] [ACF] Exception in command: re info
[14:59:24 ERROR]: [RealEstate] [ACF] java.lang.NullPointerException: Cannot invoke "me.ryanhamshire.GriefPrevention.Claim.getID()" because "this.claim" is null
[14:59:24 ERROR]: [RealEstate] [ACF]    at RealEstate-1.5.0-pre1.jar//me.EtienneDx.RealEstate.ClaimAPI.GriefPrevention.GPClaim.getId(GPClaim.java:31)
[14:59:24 ERROR]: [RealEstate] [ACF]    at RealEstate-1.5.0-pre1.jar//me.EtienneDx.RealEstate.Transactions.TransactionsStore.anyTransaction(TransactionsStore.java:155)
[14:59:24 ERROR]: [RealEstate] [ACF]    at RealEstate-1.5.0-pre1.jar//me.EtienneDx.RealEstate.RECommand.info(RECommand.java:41)
[14:59:24 ERROR]: [RealEstate] [ACF]    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:59:24 ERROR]: [RealEstate] [ACF]    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[14:59:24 ERROR]: [RealEstate] [ACF]    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:59:24 ERROR]: [RealEstate] [ACF]    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[14:59:24 ERROR]: [RealEstate] [ACF]    at RealEstate-1.5.0-pre1.jar//me.EtienneDx.RealEstate.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[14:59:24 ERROR]: [RealEstate] [ACF]    at RealEstate-1.5.0-pre1.jar//me.EtienneDx.RealEstate.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[14:59:24 ERROR]: [RealEstate] [ACF]    at RealEstate-1.5.0-pre1.jar//me.EtienneDx.RealEstate.acf.BaseCommand.execute(BaseCommand.java:513)
[14:59:24 ERROR]: [RealEstate] [ACF]    at RealEstate-1.5.0-pre1.jar//me.EtienneDx.RealEstate.acf.RootCommand.execute(RootCommand.java:99)
[14:59:24 ERROR]: [RealEstate] [ACF]    at RealEstate-1.5.0-pre1.jar//me.EtienneDx.RealEstate.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[14:59:24 ERROR]: [RealEstate] [ACF]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[14:59:24 ERROR]: [RealEstate] [ACF]    at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[14:59:24 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2307)
[14:59:24 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2118)
[14:59:24 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2099)
[14:59:24 ERROR]: [RealEstate] [ACF]    at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[14:59:24 ERROR]: [RealEstate] [ACF]    at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[14:59:24 ERROR]: [RealEstate] [ACF]    at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[14:59:24 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:59:24 ERROR]: [RealEstate] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[14:59:24 ERROR]: [RealEstate] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[14:59:24 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1400)
[14:59:24 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[14:59:24 ERROR]: [RealEstate] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[14:59:24 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1377)
[14:59:24 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1370)
[14:59:24 ERROR]: [RealEstate] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[14:59:24 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1348)
[14:59:24 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1230)
[14:59:24 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[14:59:24 ERROR]: [RealEstate] [ACF]    at java.base/java.lang.Thread.run(Thread.java:833)
```

Erro in-game:
![imagem](https://i.imgur.com/HCkFEP3.png)

**Comment by FITFC** [comment]
The developer is not active in the project, due to personal occurrences.
