### ISSUE TITLE
Something's up with renting

### ISSUE THREAD

**Issue by LinusLeonard** [EtienneDx/RealEstate#76]
@tadhunt Something regarding renting seems off. Not sure if this is present only in your release or if it's present in earlier versions. I'll see if I can figure out more info of what's going on. I created several claims a while back to test renting, leasing, and auctioning. I let my bot account rent the claim that was for rent, but I unfortunately didn't keep proper track of which claim was for rent, so I'm not sure what can be the issue here. Any way to get more info than the stack trace below? 

[17:15:13 WARN]: [RealEstate] Task #188 for RealEstate v1.5.0-pre2-MCPD-3 generated an exception
java.lang.NullPointerException: Cannot invoke "me.EtienneDx.RealEstate.ClaimAPI.IClaim.isParentClaim()" because the return value of "me.EtienneDx.RealEstate.ClaimAPI.IClaimAPI.getClaimAt(org.bukkit.Location)" is null
        at me.EtienneDx.RealEstate.Transactions.ClaimRent.payRent(ClaimRent.java:182) ~[RealEstate-1.5.0-pre2-MCPD-3.jar:?]
        at me.EtienneDx.RealEstate.Transactions.ClaimRent.update(ClaimRent.java:131) ~[RealEstate-1.5.0-pre2-MCPD-3.jar:?]
        at me.EtienneDx.RealEstate.Transactions.TransactionsStore$1.run(TransactionsStore.java:50) ~[RealEstate-1.5.0-pre2-MCPD-3.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1470) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by LinusLeonard** [comment]
Message repeats itself periodically, and comes back with the same task number (188 in this case) even after restarting server.

**Comment by tadhunt** [comment]
I won't have time to look into this until sometime in January, but from the stacktrace it looks like the root cause of the issue is that it failed to find a grief prevention claim for the real estate plot being paid rent on.  This might indicate that the two databases (grief prevention's and real estate plugin's don't match.  Maybe try starting over with empty configurations for Grief Prevention and Real Estate?

**Comment by LinusLeonard** [comment]
Thanks, I'll have a look
