### ISSUE TITLE
StringIndexOutOfBoundsException in ClaimRent task

### ISSUE THREAD

**Issue by SpencerSharkey** [EtienneDx/RealEstate#8]
```[10:59:43 WARN]: [RealEstate] Task #124 for RealEstate v0.2.0-SNAPSHOT generated an exception
java.lang.StringIndexOutOfBoundsException: String index out of range: 16
        at java.lang.String.substring(String.java:1963) ~[?:1.8.0_212]
        at me.EtienneDx.RealEstate.Transactions.ClaimRent.update(ClaimRent.java:110) ~[?:?]
        at me.EtienneDx.RealEstate.Transactions.TransactionsStore$1.run(TransactionsStore.java:45) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by EtienneDx** [comment]
Duly noted, will be patch in next update

**Comment by EtienneDx** [comment]
Fixed in release 0.3.2-SNAPSHOT

**Comment by SpencerSharkey** [comment]
I was going to patch it but I was noting it for reference, you the man! ty.

**Comment by SpencerSharkey** [comment]
Did you upstream the patch to master?

**Comment by EtienneDx** [comment]
I did yes, and released a new version out of it :)

**Comment by EtienneDx** [comment]
oops, just saw I didn't :/
give me a minute x)
